"""GTK4 Activity Manager model backed by Jarabe's registry.

Removal deliberately reuses Aspartame's recoverable quarantine policy for user
bundles and the native approval/remover boundary for system bundles.
"""

import json
import os
import shutil
import subprocess
import time

from jarabe.model import bundleregistry

from cpsection.activities import wongbaker


UAC_APPROVER = '/usr/local/libexec/aspartame-sudo-askpass'
SYSTEM_REMOVER = '/usr/local/libexec/aspartame-remove-activity'
USER_ROOT = os.path.realpath(os.path.expanduser(
    '~/.local/share/sugar/activities'))
QUARANTINE_ROOT = os.path.expanduser(
    '~/.local/share/aspartame/removed-activities')
MANAGED_ROOTS = (
    '/usr/share/sugar/activities',
    '/usr/share/aspartame/activities',
    '/usr/local/share/sugar/activities',
    '/usr/lib/sugar/activities',
)


PORT_STATUS_FILE = os.path.join(os.path.dirname(__file__), 'port_status.json')


def load_port_status(filename=PORT_STATUS_FILE):
    """Port class and side-by-side parity per bundle id (generated by
    ``scripts/sugar-parity.py export``); empty when the file is missing."""
    try:
        with open(filename, encoding='utf-8') as stream:
            data = json.load(stream)
        activities = data.get('activities', {})
    except (OSError, ValueError, AttributeError):
        return {}
    return activities if isinstance(activities, dict) else {}


def load_ratings():
    return wongbaker.load_ratings()


def save_rating(activity_id, score):
    wongbaker.save_rating(activity_id, score)


def list_activities():
    registry = bundleregistry.get_registry()
    activities = []
    for bundle in registry:
        try:
            bundle_id = bundle.get_bundle_id()
            name = bundle.get_name()
            version = bundle.get_activity_version()
            path = bundle.get_path()
        except Exception:
            continue
        activities.append({
            'id': str(bundle_id),
            'name': str(name or bundle_id),
            'version': str(version),
            'path': str(path),
            'managed': str(path).startswith(MANAGED_ROOTS),
        })
    return sorted(activities, key=lambda item: item['name'].casefold())


def remove_activity(path, quarantine=QUARANTINE_ROOT):
    """Remove a bundle safely, retaining user bundles for recovery.

    System-managed bundles can only be changed through the fullscreen Sugar
    approval helper and the constrained native remover. No recursive delete is
    performed here.
    """
    path = os.path.realpath(path)
    if not os.path.isdir(os.path.join(path, 'activity')):
        raise ValueError('That Activity bundle is not valid.')
    registry = bundleregistry.get_registry()
    if path.startswith(USER_ROOT + os.sep):
        os.makedirs(quarantine, mode=0o700, exist_ok=True)
        target = os.path.join(
            quarantine, '%d-%s' % (time.time_ns(), os.path.basename(path)))
        shutil.move(path, target)
        _forget_registry_bundle(registry, path)
        return target
    if not any(path.startswith(os.path.realpath(root) + os.sep)
               for root in MANAGED_ROOTS):
        raise PermissionError('That Activity is outside a managed Activity folder.')
    approval = subprocess.run([UAC_APPROVER], capture_output=True, text=True)
    if approval.returncode:
        raise PermissionError('Approval was cancelled.')
    result = subprocess.run(
        ['sudo', '-n', SYSTEM_REMOVER, path], capture_output=True, text=True)
    if result.returncode:
        raise PermissionError(result.stderr.strip() or 'Approval was cancelled.')
    _forget_registry_bundle(registry, path)
    return result.stdout.strip() or path


def _forget_registry_bundle(registry, path):
    """Drop a removed bundle from the live registry, when supported."""
    remover = getattr(registry, 'remove_bundle', None)
    if remover is None:
        return
    try:
        remover(path, emit_signals=True)
    except (OSError, ValueError, RuntimeError):
        # Filesystem/remover success is authoritative; an already-refreshed
        # registry must not turn a completed removal into an error.
        return
